const path = require('node:path');

const rspack = require('@rspack-template/core');

const compiler = rspack({
  context: __dirname,
  mode: 'development',
  entry: {
    main: './src/index.js',
  },
  output: {
    path: path.resolve(__dirname, 'dist'),
  },
  plugins: [new rspack.MyBannerPlugin(
    '/** Generated by MyBannerPlugin in `@rspack-template/binding` */'
  )],
});

compiler.run((err, stats) => {
  if (err) {
    console.error(err);
    process.exit(1)
  }
  console.info(stats.toString({ colors: true }));
  process.exit(0)
  compiler.close((err) => {
    if (err) {
      console.error(err)
      process.exit(1)
    }
    process.exit(0)
  })
});
